#Install Git

- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

 
  tasks:

    - name: Ensure git's dependencies are installed (Debian).
      apt: "name={{ item }} state=installed"
      with_items:
        - libcurl4-gnutls-dev
        - libexpat1-dev
        - gettext
        - libssl-dev
        - build-essential
        - gcc
      when: ansible_os_family == 'Debian'

    - name: Get installed version
      command: >
        git --version
        warn=no
      changed_when: false
      failed_when: false
      check_mode: no
      register: git_installed_version

    - name: Download git.
      get_url:
        url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
        dest: "{{ workspace }}/git-{{ git_version }}.tar.gz"
        when:  git_installed_version|failed or git_reinstall_from_source

    - name: Expand git archive.
      unarchive:
        src: "{{ workspace }}/git-{{ git_version }}.tar.gz"
        dest: "{{ workspace }}"
        creates: "{{ workspace }}/git-{{ git_version }}/README"
        copy: no
      when:  git_installed_version|failed or git_reinstall_from_source

    - name: Build git.
      command: >
        make prefix={{ git_install_path }} {{ item }}
        chdir={{ workspace }}/git-{{ git_version }}
      with_items:
        - all
        - install
      when:  git_installed_version|failed or git_reinstall_from_source
      become: yes

