#Ansible playbook for provisioning Python2, nginx, php7

- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

 
  pre_tasks:
   # add php7 repo
   - name: "Add repository for PHP 7.0."
     apt_repository:
        repo="ppa:ondrej/php"
        update_cache=yes

  tasks:

    # Upgrade packages
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    # Prerequisites
    - name: install libs
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - git
        - curl
        - python-software-properties
        - python-pip
        - python-dev
        - nginx
        - supervisor
      notify: start nginx

      #python2 dependencies
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

    - name: disable default nginx host
      file: dest=/etc/nginx/sites-enabled/default state=absent

  handlers:
    - name: start nginx
      service: name=nginx state=started

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php-fpm
      service: name=php7-fpm state=restarted


    #Still in development
