#Ansible playbook for provisioning and installing Laravel + dependencies on
#remote platform. Included: Python2, nginx, php5.5,composer, Memcached,
#redis, redis-server, redis-commander, mysql, postgreSQL, Beanstalk+console,
#gruntjs, & Laravel

- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false

 
  pre_tasks:
   # add php7 repo
   - name: "Add repository for PHP 7.0."
     apt_repository:
        repo="ppa:ondrej/php"
        update_cache=yes

  tasks:

    # Upgrade packages
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    # Prerequisites
    - name: install libs
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - git
        - curl
        - python-software-properties
        - python-pip
        - python-dev
        - nginx
        - supervisor
      notify: start nginx

      #python2 dependencies
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

 #    Composer not working with this one
 #   - name: install composer
 #     shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
 #   - name: configure composer
 #     shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer

    # Memcached
    - name: install memcached
      apt: name=memcached state=present

    # Redis
    - name: install redis server
      apt: name=redis-server state=present

    # MySQL
    - name: install mysql server
      apt: name=mysql-server state=present

    # PostgreSQL
    - name: install postgres server
      apt: name=postgresql

    # Beanstalkd
    - name: install beanstalkd
      apt: name=beanstalkd

    # Beanstalkd Console
    - name: clone beanstalkd-console
      git: repo=https://github.com/ptrofimov/beanstalk_console.git dest=/srv/beanstalkd

    - name: configure beanstalkd php-fpm pool
      template: src=files/beanstalkd.php-fpm dest=/etc/php5/fpm/pool.d/beanstalkd.conf
      notify: restart php-fpm

    - name: configure beanstalkd nginx host
      template: src=files/beanstalkd.nginx dest=/etc/nginx/sites-available/beanstalkd

    # GruntJS
    - name: install gruntjs
      npm: name=grunt-cli state=present global=yes

    # Redis Commander
    - name: install redis commander
      npm: name=redis-commander state=present global=yes

    - name: configure redis commander supervisor
      template: src=files/redis.supervisor dest=/etc/supervisor/conf.d/redis.conf
      notify: reload redis-commander

    - name: configure redis commander nginx host
      template: src=files/redis.nginx dest=/etc/nginx/sites-available/redis

    # Laravel app!
    - name: configure laravel php-fpm pool
      template: src=files/laravel.php-fpm dest=/etc/php5/fpm/pool.d/laravel.conf
      notify: restart php-fpm

    - name: configure laravel nginx host
      template: src=files/laravel.nginx dest=/etc/nginx/sites-available/laravel

    # Fabric
    - name: install fabric
      pip: name=fabric state=present

    # PECLs
    #- shell: sudo pecl install {{ item }}
    #  with_items:
    #    - pecl_http

    - name: disable default nginx host
      file: dest=/etc/nginx/sites-enabled/default state=absent

    - name: enable nginx hosts
      file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
      with_items:
        - beanstalkd
        - redis
        - laravel
      notify: restart nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

    - name: start php-fpm
      service: name=php5-fpm state=started

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php-fpm
      service: name=php5-fpm state=restarted

    - name: reload redis-commander
      supervisorctl: name=redis state=started

    #Still in development
